---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: svp-rabbit-pvc-data
  labels:
    app: svp-rabbit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: svp-rabbit-pvc-logs
  labels:
    app: svp-rabbit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
