"""Add harvester_version to reference

Revision ID: 0565e80223a7
Revises: 5ed3be5dca82
Create Date: 2024-04-09 13:39:22.784861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0565e80223a7'
down_revision: Union[str, None] = '5ed3be5dca82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('harvester_version', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'harvester_version')
    # ### end Alembic commands ###
