"""Add book

Revision ID: 05cec8971375
Revises: 4ed9b20de12f
Create Date: 2024-04-03 15:49:58.085051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05cec8971375'
down_revision: Union[str, None] = '4ed9b20de12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('isbn10', sa.String(), nullable=True),
    sa.Column('isbn13', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_isbn10'), 'books', ['isbn10'], unique=True)
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=True)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.add_column('references', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'references', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'references', type_='foreignkey')
    op.drop_column('references', 'book_id')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.drop_index(op.f('ix_books_isbn10'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
