"""Allow null values has contributor source identifiers

Revision ID: 0f7d69c4bad7
Revises: e4e70431c2dc
Create Date: 2023-11-17 09:28:31.884471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7d69c4bad7'
down_revision: Union[str, None] = 'e4e70431c2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contributors', 'source_identifier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contributors', 'source_identifier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
