"""add states enum to harvesters

Revision ID: 13949ed5b55c
Revises: 5aadf4c08b01
Create Date: 2023-09-13 08:53:27.786993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13949ed5b55c'
down_revision: Union[str, None] = '5aadf4c08b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvestings', sa.Column('state', sa.String(), nullable=False))
    op.create_index(op.f('ix_harvestings_state'), 'harvestings', ['state'], unique=False)
    op.alter_column('people', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('people', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('people', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_harvestings_state'), table_name='harvestings')
    op.drop_column('harvestings', 'state')
    # ### end Alembic commands ###
