"""Add entities, people, identifiers to the model

Revision ID: 1fc53c666a86
Revises: 975f9054c720
Create Date: 2023-09-08 15:43:58.468730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc53c666a86'
down_revision: Union[str, None] = '975f9054c720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identifiers_id'), 'identifiers', ['id'], unique=False)
    op.create_index(op.f('ix_identifiers_type'), 'identifiers', ['type'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('retrievals', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'retrievals', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retrievals', type_='foreignkey')
    op.drop_column('retrievals', 'entity_id')
    op.drop_table('people')
    op.drop_index(op.f('ix_identifiers_type'), table_name='identifiers')
    op.drop_index(op.f('ix_identifiers_id'), table_name='identifiers')
    op.drop_table('identifiers')
    op.drop_table('entities')
    # ### end Alembic commands ###
