"""Add references and reference events

Revision ID: 20409156f887
Revises: 1fc53c666a86
Create Date: 2023-09-08 16:00:17.909642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20409156f887'
down_revision: Union[str, None] = '1fc53c666a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_hash'), 'references', ['hash'], unique=False)
    op.create_index(op.f('ix_references_id'), 'references', ['id'], unique=False)
    op.create_table('reference_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('harvesting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['harvesting_id'], ['harvestings.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_events_id'), 'reference_events', ['id'], unique=False)
    op.create_index(op.f('ix_reference_events_type'), 'reference_events', ['type'], unique=False)
    op.add_column('harvestings', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvestings', 'timestamp')
    op.drop_index(op.f('ix_reference_events_type'), table_name='reference_events')
    op.drop_index(op.f('ix_reference_events_id'), table_name='reference_events')
    op.drop_table('reference_events')
    op.drop_index(op.f('ix_references_id'), table_name='references')
    op.drop_index(op.f('ix_references_hash'), table_name='references')
    op.drop_table('references')
    # ### end Alembic commands ###
