"""Add hal_submit_type field to reference

Revision ID: 211d693e0fe3
Revises: 55c3c9f3ee4a
Create Date: 2025-05-22 03:02:12.376162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211d693e0fe3'
down_revision: Union[str, None] = '55c3c9f3ee4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('hal_submit_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'hal_submit_type')
    # ### end Alembic commands ###
