"""Add unique index to identifiers

Revision ID: 2af6cb761f0d
Revises: b62fef73db09
Create Date: 2023-10-14 06:45:28.161422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af6cb761f0d'
down_revision: Union[str, None] = 'b62fef73db09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'identifiers', ['type', 'value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'identifiers', type_='unique')
    # ### end Alembic commands ###
