"""Change unique constraints on isbn10-source and isbn13-source

Revision ID: 2cdd75e33246
Revises: 5dd94d035a91
Create Date: 2024-06-04 15:35:02.925982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdd75e33246'
down_revision: Union[str, None] = '5dd94d035a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_isbn10', table_name='books')
    op.create_index(op.f('ix_books_isbn10'), 'books', ['isbn10'], unique=False)
    op.drop_index('ix_books_isbn13', table_name='books')
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=False)
    op.create_unique_constraint('_isbn10_source_uc', 'books', ['isbn10', 'source'])
    op.create_unique_constraint('_isbn13_source_uc', 'books', ['isbn13', 'source'])
    op.create_index(op.f('ix_contributions_id'), 'contributions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributions_id'), table_name='contributions')
    op.drop_constraint('_isbn13_source_uc', 'books', type_='unique')
    op.drop_constraint('_isbn10_source_uc', 'books', type_='unique')
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.create_index('ix_books_isbn13', 'books', ['isbn13'], unique=False)
    op.drop_index(op.f('ix_books_isbn10'), table_name='books')
    op.create_index('ix_books_isbn10', 'books', ['isbn10'], unique=False)
    # ### end Alembic commands ###
