"""Add event_types filter to Retrieval model

Revision ID: 31912c99fa2a
Revises: 2af6cb761f0d
Create Date: 2023-10-19 06:55:47.033047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31912c99fa2a'
down_revision: Union[str, None] = '2af6cb761f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retrievals', sa.Column('event_types', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retrievals', 'event_types')
    # ### end Alembic commands ###
