"""add unique constraint to contributor model

Revision ID: 352109cd8dd5
Revises: 4c96f2c87560
Create Date: 2024-01-25 13:55:09.594076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "352109cd8dd5"
down_revision: Union[str, None] = "4c96f2c87560"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "contributors", ["source", "source_identifier"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contributors", type_="unique")
    # ### end Alembic commands ###
