"""add_identifier_used_to_harvesting

Revision ID: 3867058e77a9
Revises: 8a5176c45e86
Create Date: 2026-04-28 07:32:56.378626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3867058e77a9'
down_revision: Union[str, None] = '8a5176c45e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvestings', sa.Column('identifier_used_type', sa.String(), nullable=True))
    op.add_column('harvestings', sa.Column('identifier_used_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvestings', 'identifier_used_value')
    op.drop_column('harvestings', 'identifier_used_type')
    # ### end Alembic commands ###
