"""Add history field to harvestings

Revision ID: 472729c5be0e
Revises: 82dd85d0b650
Create Date: 2023-10-20 04:20:28.795027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472729c5be0e'
down_revision: Union[str, None] = '82dd85d0b650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvestings', sa.Column('history', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_harvestings_history'), 'harvestings', ['history'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harvestings_history'), table_name='harvestings')
    op.drop_column('harvestings', 'history')
    # ### end Alembic commands ###
