"""Add unique index to issues

Revision ID: 4ed9b20de12f
Revises: 26bb2c22515d
Create Date: 2024-03-30 18:20:11.304948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed9b20de12f'
down_revision: Union[str, None] = '26bb2c22515d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'issues', ['source', 'source_identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='unique')
    # ### end Alembic commands ###
