"""Add hal_collection_codes field to reference

Revision ID: 55c3c9f3ee4a
Revises: b4ce17110a72
Create Date: 2025-05-21 21:17:26.978911

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55c3c9f3ee4a"
down_revision: Union[str, None] = "b4ce17110a72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "references",
        sa.Column(
            "hal_collection_codes",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default="{}",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("references", "hal_collection_codes")
    # ### end Alembic commands ###
