"""add topics and reference_topics tables

Revision ID: 599ca6b25c7b
Revises: 3867058e77a9
Create Date: 2026-05-25 11:49:29.603904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599ca6b25c7b'
down_revision: Union[str, None] = '3867058e77a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_topics_source_id'), 'topics', ['source_id'], unique=True)
    op.create_table('reference_topics',
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('reference_id', 'topic_id')
    )
    op.create_index(op.f('ix_reference_topics_reference_id'), 'reference_topics', ['reference_id'], unique=False)
    op.create_index(op.f('ix_reference_topics_topic_id'), 'reference_topics', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_topics_topic_id'), table_name='reference_topics')
    op.drop_index(op.f('ix_reference_topics_reference_id'), table_name='reference_topics')
    op.drop_table('reference_topics')
    op.drop_index(op.f('ix_topics_source_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
