"""Add unique constraint to contributors

Revision ID: 5b345b1cf9fd
Revises: b272f63e0548
Create Date: 2024-03-04 06:53:45.062910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b345b1cf9fd'
down_revision: Union[str, None] = 'b272f63e0548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contributors_source_source_identifier_key', 'contributors', type_='unique')
    op.create_unique_constraint(None, 'contributors', ['source', 'source_identifier', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contributors', type_='unique')
    op.create_unique_constraint('contributors_source_source_identifier_key', 'contributors', ['source', 'source_identifier'])
    # ### end Alembic commands ###
