"""Add enhanced bool to reference event

Revision ID: 5dd94d035a91
Revises: d6e2f2b74de7
Create Date: 2024-04-09 13:53:42.666413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd94d035a91'
down_revision: Union[str, None] = 'd6e2f2b74de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_events', sa.Column('enhanced', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_events', 'enhanced')
    # ### end Alembic commands ###
