"""Add book source

Revision ID: 5ed3be5dca82
Revises: 8df137c3dfb3
Create Date: 2024-04-09 10:44:27.487602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed3be5dca82'
down_revision: Union[str, None] = '8df137c3dfb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('source', sa.String(), nullable=False))
    op.create_index(op.f('ix_books_source'), 'books', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_source'), table_name='books')
    op.drop_column('books', 'source')
    # ### end Alembic commands ###
