"""Update indexed fields

Revision ID: 64e06961ec1e
Revises: a0fb77b73783
Create Date: 2024-01-17 09:39:31.828056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e06961ec1e'
down_revision: Union[str, None] = 'a0fb77b73783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contributors_name'), 'contributors', ['name'], unique=False)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_literal_fields_value'), 'literal_fields', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_literal_fields_value'), table_name='literal_fields')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index(op.f('ix_contributors_name'), table_name='contributors')
    # ### end Alembic commands ###
