"""Add timestamp to Retrieval

Revision ID: 6d0387871d88
Revises: 352109cd8dd5
Create Date: 2024-02-02 10:18:05.463919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0387871d88'
down_revision: Union[str, None] = '352109cd8dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retrievals', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retrievals', 'timestamp')
    # ### end Alembic commands ###
