"""Add issn_l, change cardinalities issn, eissn

Revision ID: 7e00006b7258
Revises: 9819430670b6
Create Date: 2024-03-20 11:30:29.759851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7e00006b7258"
down_revision: Union[str, None] = "9819430670b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("journals", sa.Column("issn_l", sa.String(), nullable=True))
    op.execute(
        "ALTER TABLE journals ALTER COLUMN issn TYPE VARCHAR[] USING issn::character varying[]"
    )
    op.execute(
        "ALTER TABLE journals ALTER COLUMN eissn TYPE VARCHAR[] USING eissn::character varying[]"
    )
    op.alter_column("journals", "issn", nullable=False)
    op.alter_column("journals", "eissn", nullable=False)
    op.create_index(op.f("ix_journals_issn_l"), "journals", ["issn_l"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journals_issn_l"), table_name="journals")
    op.alter_column("journals", "eissn", type_=sa.VARCHAR(), nullable=True)
    op.alter_column("journals", "issn", type_=sa.VARCHAR(), nullable=True)
    op.drop_column("journals", "issn_l")
    # ### end Alembic commands ###
