"""Reference Date

Revision ID: 7e5a6084ab57
Revises: 0a608b9c4070
Create Date: 2024-02-15 13:51:07.394156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5a6084ab57'
down_revision: Union[str, None] = '0a608b9c4070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('issued', sa.DateTime(), nullable=True))
    op.add_column('references', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_references_created'), 'references', ['created'], unique=False)
    op.create_index(op.f('ix_references_issued'), 'references', ['issued'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_references_issued'), table_name='references')
    op.drop_index(op.f('ix_references_created'), table_name='references')
    op.drop_column('references', 'created')
    op.drop_column('references', 'issued')
    # ### end Alembic commands ###
