"""Add history field to reference events

Revision ID: 82dd85d0b650
Revises: 31912c99fa2a
Create Date: 2023-10-20 03:40:40.158264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dd85d0b650'
down_revision: Union[str, None] = '31912c99fa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_events', sa.Column('history', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_reference_events_history'), 'reference_events', ['history'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_events_history'), table_name='reference_events')
    op.drop_column('reference_events', 'history')
    # ### end Alembic commands ###
