"""Update database schema with reference_literal_fields_refacto

Revision ID: 87424e42b54c
Revises: 6b0c405a36a9
Create Date: 2024-02-03 11:47:15.729987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87424e42b54c'
down_revision: Union[str, None] = '6b0c405a36a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_language'), 'subtitles', ['language'], unique=False)
    op.create_index(op.f('ix_subtitles_value'), 'subtitles', ['value'], unique=False)
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_language'), 'titles', ['language'], unique=False)
    op.create_index(op.f('ix_titles_value'), 'titles', ['value'], unique=False)
    op.drop_index('ix_reference_literal_fields_language', table_name='reference_literal_fields')
    op.drop_index('ix_reference_literal_fields_value', table_name='reference_literal_fields')
    op.drop_table('reference_literal_fields')
    op.drop_index('ix_abstracts_value', table_name='abstracts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_abstracts_value', 'abstracts', ['value'], unique=False)
    op.create_table('reference_literal_fields',
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], name='reference_literal_fields_reference_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reference_literal_fields_pkey')
    )
    op.create_index('ix_reference_literal_fields_value', 'reference_literal_fields', ['value'], unique=False)
    op.create_index('ix_reference_literal_fields_language', 'reference_literal_fields', ['language'], unique=False)
    op.drop_index(op.f('ix_titles_value'), table_name='titles')
    op.drop_index(op.f('ix_titles_language'), table_name='titles')
    op.drop_table('titles')
    op.drop_index(op.f('ix_subtitles_value'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_language'), table_name='subtitles')
    op.drop_table('subtitles')
    # ### end Alembic commands ###
