"""Add extra informations to organization identifiers

Revision ID: 8a5176c45e86
Revises: eebf1bb1511f
Create Date: 2025-12-30 10:27:46.720575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a5176c45e86'
down_revision: Union[str, None] = 'eebf1bb1511f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_identifiers', sa.Column('extra_information', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_identifiers', 'extra_information')
    # ### end Alembic commands ###
