"""Add  Harvesting model

Revision ID: 975f9054c720
Revises: 3cccb8eec883
Create Date: 2023-09-08 08:14:43.783518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975f9054c720'
down_revision: Union[str, None] = '3cccb8eec883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvestings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvester', sa.String(), nullable=True),
    sa.Column('retrieval_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['retrieval_id'], ['retrievals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvestings_harvester'), 'harvestings', ['harvester'], unique=False)
    op.create_index(op.f('ix_harvestings_id'), 'harvestings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harvestings_id'), table_name='harvestings')
    op.drop_index(op.f('ix_harvestings_harvester'), table_name='harvestings')
    op.drop_table('harvestings')
    # ### end Alembic commands ###
