"""Add page to reference, titles to issue

Revision ID: 9819430670b6
Revises: e38e811b4963
Create Date: 2024-03-15 11:20:58.363711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9819430670b6'
down_revision: Union[str, None] = 'e38e811b4963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('titles', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('references', sa.Column('page', sa.String(), nullable=True))
    op.create_index(op.f('ix_references_page'), 'references', ['page'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_references_page'), table_name='references')
    op.drop_column('references', 'page')
    op.drop_column('issues', 'titles')
    # ### end Alembic commands ###
