"""Add name variants fields in contributor db entity

Revision ID: a0fb77b73783
Revises: 0f7d69c4bad7
Create Date: 2023-11-22 09:36:16.610820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0fb77b73783'
down_revision: Union[str, None] = '0f7d69c4bad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributors', sa.Column('name_variants', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributors', 'name_variants')
    # ### end Alembic commands ###
