"""Add version number to references

Revision ID: a48008ad7444
Revises: 2248a9928bed
Create Date: 2023-10-13 07:29:08.207819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48008ad7444'
down_revision: Union[str, None] = '2248a9928bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('version', sa.Integer(), nullable=False))
    op.drop_index('ix_references_hash', table_name='references')
    op.create_index(op.f('ix_references_version'), 'references', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_references_version'), table_name='references')
    op.create_index('ix_references_hash', 'references', ['hash'], unique=False)
    op.drop_column('references', 'version')
    # ### end Alembic commands ###
