"""Add unique index to document types

Revision ID: a60cf7db9469
Revises: 87424e42b54c
Create Date: 2024-02-03 11:47:39.152452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60cf7db9469'
down_revision: Union[str, None] = '87424e42b54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_types_uri_key', 'document_types', type_='unique')
    op.create_index(op.f('ix_document_types_uri'), 'document_types', ['uri'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_types_uri'), table_name='document_types')
    op.create_unique_constraint('document_types_uri_key', 'document_types', ['uri'])
    # ### end Alembic commands ###
