"""Duplicate harvester name to reference

Revision ID: b62fef73db09
Revises: a48008ad7444
Create Date: 2023-10-13 08:44:11.952135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62fef73db09'
down_revision: Union[str, None] = 'a48008ad7444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('harvester', sa.String(), nullable=False))
    op.create_index(op.f('ix_references_harvester'), 'references', ['harvester'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_references_harvester'), table_name='references')
    op.drop_column('references', 'harvester')
    # ### end Alembic commands ###
