"""Add dereferencing information to concepts

Revision ID: bbd6b48431fe
Revises: 4c96f2c87560
Create Date: 2024-01-27 07:30:42.574095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd6b48431fe'
down_revision: Union[str, None] = '4c96f2c87560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('dereferenced', sa.Boolean(), nullable=False))
    op.add_column('concepts', sa.Column('last_dereferencing_date_time', sa.DateTime(), nullable=True))
    op.drop_constraint('concepts_uri_key', 'concepts', type_='unique')
    op.create_index(op.f('ix_concepts_uri'), 'concepts', ['uri'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concepts_uri'), table_name='concepts')
    op.create_unique_constraint('concepts_uri_key', 'concepts', ['uri'])
    op.drop_column('concepts', 'last_dereferencing_date_time')
    op.drop_column('concepts', 'dereferenced')
    # ### end Alembic commands ###
