"""Reference Identifier

Revision ID: c92b114e1074
Revises: dc72ae6ea810
Create Date: 2024-02-09 16:32:06.888859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92b114e1074'
down_revision: Union[str, None] = 'dc72ae6ea810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_identifiers_type'), 'reference_identifiers', ['type'], unique=False)
    op.create_index(op.f('ix_reference_identifiers_value'), 'reference_identifiers', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_identifiers_value'), table_name='reference_identifiers')
    op.drop_index(op.f('ix_reference_identifiers_type'), table_name='reference_identifiers')
    op.drop_table('reference_identifiers')
    # ### end Alembic commands ###
