"""Add unique constraints to contributors

Revision ID: d4047a91b450
Revises: b272f63e0548
Create Date: 2024-03-04 09:49:53.274769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4047a91b450'
down_revision: Union[str, None] = 'b272f63e0548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contributors_source_source_identifier_key', 'contributors', type_='unique')
    op.create_index('unique_name_per_source_if_no_identifier', 'contributors', ['source', 'name'], unique=False, postgresql_where=sa.text('source_identifier IS NULL'))
    op.create_index('unique_source_identifier_per_source', 'contributors', ['source', 'source_identifier'], unique=True, postgresql_where=sa.text('source_identifier IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_source_identifier_per_source', table_name='contributors', postgresql_where=sa.text('source_identifier IS NOT NULL'))
    op.drop_index('unique_name_per_source_if_no_identifier', table_name='contributors', postgresql_where=sa.text('source_identifier IS NULL'))
    op.create_unique_constraint('contributors_source_source_identifier_key', 'contributors', ['source', 'source_identifier'])
    # ### end Alembic commands ###
