"""Add harvester version

Revision ID: d6e2f2b74de7
Revises: 5ed3be5dca82
Create Date: 2024-04-09 13:53:11.636784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e2f2b74de7'
down_revision: Union[str, None] = '5ed3be5dca82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('harvester_version', sa.String(), server_default='0.0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'harvester_version')
    # ### end Alembic commands ###
