"""Add full name to Person model

Revision ID: d7c7fdb5e754
Revises: e986b5e7c149
Create Date: 2023-10-10 10:15:11.764210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c7fdb5e754'
down_revision: Union[str, None] = 'e986b5e7c149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'full_name')
    # ### end Alembic commands ###
