"""Organization Type

Revision ID: e076be276210
Revises: f0231f97fd0b
Create Date: 2024-02-16 17:15:47.477041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e076be276210'
down_revision: Union[str, None] = 'f0231f97fd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('type', sa.String(), nullable=False))
    op.create_index(op.f('ix_organizations_type'), 'organizations', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_type'), table_name='organizations')
    op.drop_column('organizations', 'type')
    # ### end Alembic commands ###
