"""Add issue and journal models

Revision ID: e38e811b4963
Revises: 56efe00e9d63
Create Date: 2024-03-06 11:26:23.260449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e38e811b4963'
down_revision: Union[str, None] = '56efe00e9d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_identifier', sa.String(), nullable=False),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('eissn', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('titles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_eissn'), 'journals', ['eissn'], unique=False)
    op.create_index(op.f('ix_journals_issn'), 'journals', ['issn'], unique=False)
    op.create_index(op.f('ix_journals_source'), 'journals', ['source'], unique=False)
    op.create_index(op.f('ix_journals_source_identifier'), 'journals', ['source_identifier'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_identifier', sa.String(), nullable=False),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('number', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('rights', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_date'), 'issues', ['date'], unique=False)
    op.create_index(op.f('ix_issues_source'), 'issues', ['source'], unique=False)
    op.create_index(op.f('ix_issues_source_identifier'), 'issues', ['source_identifier'], unique=False)
    op.create_index(op.f('ix_issues_volume'), 'issues', ['volume'], unique=False)
    op.add_column('references', sa.Column('issue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'references', 'issues', ['issue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'references', type_='foreignkey')
    op.drop_column('references', 'issue_id')
    op.drop_index(op.f('ix_issues_volume'), table_name='issues')
    op.drop_index(op.f('ix_issues_source_identifier'), table_name='issues')
    op.drop_index(op.f('ix_issues_source'), table_name='issues')
    op.drop_index(op.f('ix_issues_date'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_journals_source_identifier'), table_name='journals')
    op.drop_index(op.f('ix_journals_source'), table_name='journals')
    op.drop_index(op.f('ix_journals_issn'), table_name='journals')
    op.drop_index(op.f('ix_journals_eissn'), table_name='journals')
    op.drop_table('journals')
    # ### end Alembic commands ###
