"""Add entities for affiliations

Revision ID: e4e70431c2dc
Revises: 9cd506ac9da5
Create Date: 2023-11-16 10:04:28.739346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e70431c2dc'
down_revision: Union[str, None] = '9cd506ac9da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_source'), 'organizations', ['source'], unique=False)
    op.create_index(op.f('ix_organizations_source_identifier'), 'organizations', ['source_identifier'], unique=False)
    op.create_table('affiliations_table',
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliations_table')
    op.drop_index(op.f('ix_organizations_source_identifier'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_source'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
