"""Add custom_metadata field to Reference

Revision ID: eebf1bb1511f
Revises: b4ce17110a72
Create Date: 2025-05-22 21:57:51.900017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebf1bb1511f'
down_revision: Union[str, None] = 'b4ce17110a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('custom_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'custom_metadata')
    # ### end Alembic commands ###
