"""Organization Identifier

Revision ID: f0231f97fd0b
Revises: 374cdea04cbf
Create Date: 2024-02-16 17:04:52.902223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0231f97fd0b'
down_revision: Union[str, None] = '374cdea04cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_identifiers_type'), 'organization_identifiers', ['type'], unique=False)
    op.create_index(op.f('ix_organization_identifiers_value'), 'organization_identifiers', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_identifiers_value'), table_name='organization_identifiers')
    op.drop_index(op.f('ix_organization_identifiers_type'), table_name='organization_identifiers')
    op.drop_table('organization_identifiers')
    # ### end Alembic commands ###
