"""Add error harvesting

Revision ID: f3d3bbf4e517
Revises: c18a66148821
Create Date: 2024-01-19 16:59:13.308004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d3bbf4e517'
down_revision: Union[str, None] = 'c18a66148821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvesting_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvesting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['harvesting_id'], ['harvestings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harvesting_errors')
    # ### end Alembic commands ###
