"""update primary keys

Revision ID: f6a84408b053
Revises: 64e06961ec1e
Create Date: 2024-01-18 08:45:29.012263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a84408b053'
down_revision: Union[str, None] = '64e06961ec1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_concepts_id', table_name='concepts')
    op.drop_index('ix_contributions_id', table_name='contributions')
    op.drop_index('ix_contributors_id', table_name='contributors')
    op.drop_index('ix_entities_id', table_name='entities')
    op.drop_index('ix_harvestings_id', table_name='harvestings')
    op.drop_index('ix_identifiers_id', table_name='identifiers')
    op.drop_index('ix_literal_fields_id', table_name='literal_fields')
    op.drop_index('ix_organizations_id', table_name='organizations')
    op.drop_index('ix_reference_events_id', table_name='reference_events')
    op.drop_index('ix_references_id', table_name='references')
    op.drop_index('ix_retrievals_id', table_name='retrievals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_retrievals_id', 'retrievals', ['id'], unique=False)
    op.create_index('ix_references_id', 'references', ['id'], unique=False)
    op.create_index('ix_reference_events_id', 'reference_events', ['id'], unique=False)
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    op.create_index('ix_literal_fields_id', 'literal_fields', ['id'], unique=False)
    op.create_index('ix_identifiers_id', 'identifiers', ['id'], unique=False)
    op.create_index('ix_harvestings_id', 'harvestings', ['id'], unique=False)
    op.create_index('ix_entities_id', 'entities', ['id'], unique=False)
    op.create_index('ix_contributors_id', 'contributors', ['id'], unique=False)
    op.create_index('ix_contributions_id', 'contributions', ['id'], unique=False)
    op.create_index('ix_concepts_id', 'concepts', ['id'], unique=False)
    # ### end Alembic commands ###
