apiVersion: v1
kind: Service
metadata:
  labels:
    app: svph-api
  name: svph-api-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: svph-api
  type: LoadBalancer
