apiVersion: v1
kind: Service
metadata:
  labels:
    app: svp-rabbit
  name: svp-rabbit
spec:
  ports:
    - name: "amqp-port"
      port: 5672
      targetPort: 5672
    - name: "amqp-management-port"
      port: 15672
      targetPort: 15672
  selector:
    app: svp-rabbit
status:
  loadBalancer: {}
