apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: svph-api
  name: svph-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svph-api
  strategy: { }
  template:
    metadata:
      labels:
        app: svph-api
    spec:
      containers:
        - args:
            - bash
            - -c
            - alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000
          env:
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: svp-rabbit-secret
                  key: amqppassword
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: svp-rabbit-secret
                  key: amqpuser
            - name: SCANR_ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: svph-api-secret
                  key: scanr_es_password
            - name: SCANR_ES_USER
              valueFrom:
                secretKeyRef:
                  name: svph-api-secret
                  key: scanr_es_user
            - name: SCANR_ES_HOST
              valueFrom:
                secretKeyRef:
                  name: svph-api-secret
                  key: scanr_es_host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: svph-db-secret
                  key: db_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: svph-db-secret
                  key: db_user
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: svph-db-secret
                  key: db_name
          envFrom:
            - configMapRef:
                name: svph-api-config
          image: crisalidesr/svp-harvester:v0.2-dev
          imagePullPolicy: Always
          name: svph-web
          ports:
            - containerPort: 8000
          resources: { }
      restartPolicy: Always