name: CD Push dev-main

on:
  push:
    branches:
      - 'dev-main'

jobs:
  poeditor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Generate translations files
        run: |
          pybabel extract --mapping babel.cfg --output-file=locales/admin.pot .
          pybabel update --domain=admin --input-file=locales/admin.pot --output-dir=locales
          pybabel compile --domain=admin --directory=locales --use-fuzzy

      - name: Commit files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add locales/*
          git commit -m "Update translations"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


      - name: Delete branch poeditor-translations
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: poeditor-translations
          suffix: -done

      - name: Create branch poeditor-translations
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: poeditor-translations

  docker:
    needs: poeditor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest